### ISSUE TITLE
Dowload link for Wikidata database is dead!!!

### ISSUE THREAD

**Issue by tdt98** [sigamani/ner#1]
Hello @sigamani , thank you for sharing your great work. I would like to ask if you can provide me another link for wikidata database or give me guidance for create the database. Thank you in advance!!!

**Comment by sigamani** [comment]
Hi,

does this work for you?
https://drive.google.com/file/d/1ux9n_ilbRhqX-dZgdcAzPb0S2tyAzU0-/view?usp=sharing

also, if you need, the BERT model is here:
https://drive.google.com/file/d/1VECMmwPAXyEbwOPg8weAm9nCQkmKuJcN/view?usp=sharing

m

**Comment by tdt98** [comment]
Thank you for your help. I already changed to use the Wikidata API.
