### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by kkaiser12** [sigamani/ner#2]
The link for the data is not available anymore. Is there any possibility to get the data? Or could you give an advice, how to create it?

**Comment by sigamani** [comment]
Let me see if I can find it. I've had quite a few requests.

**Comment by kkaiser12** [comment]
That would be great, thank you very much!

**Comment by sigamani** [comment]
I've looked on my laptop and cannot find it. Later this week (by Friday) I will check my harddrive backup and hope it's there. If not I guess it's lost forever :(

**Comment by sigamani** [comment]
You are in luck. I managed to find it and upload it. Please use the README and download and let me know how you get on.

**Comment by kkaiser12** [comment]
Thank you very much! I will try it.

**Comment by kkaiser12** [comment]
I got it working. I had to do these additional steps:
- update the spacy model with: `python -m spacy download en_core_web_sm` and change it in the TrueCaser class to         
`self.nlp = spacy.load('en_core_web_sm')`
- comment out the logger (somehow I didn't find a package for it anywhere.)
- installl a different version of overrides: `pip install overrides==3.1.0`

**Comment by sigamani** [comment]
Thanks I'll update the README
